// <auto-generated />
namespace Trialmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class docStarted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(docStarted));
        
        string IMigrationMetadata.Id
        {
            get { return "201809211345290_docStarted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
