// <auto-generated />
namespace Trialmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contactNotesId7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactNotesId7));
        
        string IMigrationMetadata.Id
        {
            get { return "201808201349165_contactNotesId7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
