// <auto-generated />
namespace Trialmanager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class notes3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notes3));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221252289_notes3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
